# Generated by Django 4.0.6 on 2022-09-14 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_has_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='description',
        ),
        migrations.RemoveField(
            model_name='application',
            name='name',
        ),
    ]
