# Generated by Django 4.0.6 on 2023-10-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_application_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fathers_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
