# Generated by Django 4.0.6 on 2023-10-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_country_user_mothers_name_user_place_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marital_status',
            field=models.CharField(choices=[('married', 'Married'), ('unmarried', 'Unmarried')], max_length=9, null=True),
        ),
    ]
