# Generated by Django 4.0.6 on 2023-10-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_user_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='military_service',
            field=models.CharField(choices=[('completed', 'Completed'), ('not completed', 'Not Completed')], max_length=13, null=True),
        ),
    ]
