# Generated by Django 4.0.6 on 2023-10-09 16:34

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='amka',
            field=models.CharField(max_length=11, null=True, validators=[main.models.User.validate_amka]),
        ),
    ]
