# Generated by Django 4.0.6 on 2023-10-11 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_user_amka'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='afm',
            field=models.CharField(max_length=9, null=True, validators=[main.models.User.validate_afm]),
        ),
        migrations.CreateModel(
            name='Contact_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_number', models.CharField(max_length=10, null=True, validators=[main.models.Contact_information.validate_number])),
                ('cell_number', models.CharField(max_length=10, null=True, validators=[main.models.Contact_information.validate_number])),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
