# Generated by Django 4.0.6 on 2023-10-12 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_user_afm_contact_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('married', 'Married'), ('unmarried', 'Unmarried')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='military_service',
            field=models.CharField(blank=True, choices=[('completed', 'Completed'), ('not completed', 'Not Completed')], max_length=13, null=True),
        ),
        migrations.CreateModel(
            name='Foreign_language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=150, null=True)),
                ('level', models.CharField(blank=True, max_length=150, null=True)),
                ('degree', models.CharField(max_length=150, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('acquisition_date', models.DateField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
