# Generated by Django 4.0.6 on 2023-10-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_foreign_language_user_work_experience_theses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theses',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
