# Generated by Django 4.0.6 on 2023-10-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_undergraduate_postgraduate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreign_language',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postgraduate',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='theses',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='undergraduate',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
