# Generated by Django 5.0 on 2024-01-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_postgraduate_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreign_language',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reference_letter',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='theses',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='work_experience',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
