# Generated by Django 5.0 on 2024-01-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_foreign_language_acquisition_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-updated', '-created'], 'permissions': [('validate_application', 'Can validate an application')]},
        ),
        migrations.AddField(
            model_name='application',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
