# Generated by Django 5.0 on 2024-01-14 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_application_is_accepted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-updated', '-created'], 'permissions': [('validate_application', 'Can validate an application'), ('accept_application', 'Can accept an application')]},
        ),
    ]
