# Generated by Django 5.0 on 2024-01-18 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_orientation_masters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masters',
            name='orientation',
        ),
        migrations.AddField(
            model_name='orientation',
            name='masters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.masters'),
        ),
    ]
