# Generated by Django 5.0 on 2024-01-18 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_application_masters'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='orientation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.orientation'),
        ),
    ]
