# Generated by Django 5.0 on 2024-01-19 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_application_orientation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='masters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.masters'),
        ),
        migrations.AlterField(
            model_name='application',
            name='orientation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.orientation'),
        ),
    ]
