# Generated by Django 5.0 on 2024-01-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_rename_masters_master_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_withdrawn',
            field=models.BooleanField(default=False),
        ),
    ]
