# Generated by Django 5.0 on 2024-01-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_application_is_withdrawn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='master',
        ),
    ]
