# Generated by Django 5.0 on 2024-01-25 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_application_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.master'),
        ),
    ]
