# Generated by Django 5.0 on 2024-01-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_application_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreign_language',
            name='photo',
            field=models.ImageField(null=True, upload_to='languages'),
        ),
        migrations.AddField(
            model_name='postgraduate',
            name='photo',
            field=models.ImageField(null=True, upload_to='studies'),
        ),
        migrations.AddField(
            model_name='undergraduate',
            name='photo',
            field=models.ImageField(null=True, upload_to='studies'),
        ),
    ]
