# Generated by Django 5.0 on 2024-02-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_foreign_language_photo_postgraduate_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreign_language',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='languages'),
        ),
        migrations.AlterField(
            model_name='postgraduate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='studies'),
        ),
        migrations.AlterField(
            model_name='undergraduate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='studies'),
        ),
    ]
